#include <QtTest/QtTest>
#include <QTemporaryFile>
#include <QSignalSpy>
#include <QEventLoop>
#include <QTimer>

class TestMirrorListWindow : public QObject
{
    Q_OBJECT

private:
    QString createTestMirrorList() {
        return R"(################################################################################
################# Arch Linux mirrorlist generated by Reflector ################
################################################################################

## China
#Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
#Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
#Server = https://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch

## United States
#Server = https://mirrors.mit.edu/archlinux/$repo/os/$arch
#Server = https://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch

## Germany
#Server = https://mirror.netcologne.de/archlinux/$repo/os/$arch
#Server = https://ftp.fau.de/archlinux/$repo/os/$arch
)";
    }

private slots:
    void initTestCase() {
        qDebug() << "开始 MirrorListWindow 测试";
    }

    void cleanupTestCase() {
        qDebug() << "完成 MirrorListWindow 测试";
    }

    void testParseMirrorList() {
        QString mirrorList = createTestMirrorList();
        QStringList lines = mirrorList.split("\n");
        
        QMap<QString, QStringList> countryMirrorsMap;
        
        // 模拟 MirrorListWindow 的解析逻辑
        for (int i = 0; i < lines.size(); ++i) {
            QString line = lines[i].trimmed();
            if (line.startsWith("## ")) {
                QString country = line.mid(3).trimmed();
                QStringList mirrors;
                
                for (int j = i + 1; j < lines.size(); ++j) {
                    QString mirrorLine = lines[j].trimmed();
                    if (mirrorLine.startsWith("#Server = ")) {
                        QString mirrorUrl = mirrorLine.mid(9).trimmed();
                        mirrors.append(mirrorUrl);
                    } else if (mirrorLine.startsWith("## ")) {
                        break;
                    }
                }
                
                if (!country.isEmpty() && !mirrors.isEmpty()) {
                    countryMirrorsMap[country] = mirrors;
                }
            }
        }
        
        // 验证解析结果
        QCOMPARE(countryMirrorsMap.size(), 3);
        QVERIFY(countryMirrorsMap.contains("China"));
        QVERIFY(countryMirrorsMap.contains("United States"));
        QVERIFY(countryMirrorsMap.contains("Germany"));
        
        // 验证中国镜像数量
        QCOMPARE(countryMirrorsMap["China"].size(), 3);
        QVERIFY(countryMirrorsMap["China"][0].contains("tuna.tsinghua.edu.cn"));
        
        // 验证美国镜像数量
        QCOMPARE(countryMirrorsMap["United States"].size(), 2);
        
        // 验证德国镜像数量
        QCOMPARE(countryMirrorsMap["Germany"].size(), 2);
    }

    void testCheckRateMirrorsInstalled() {
        // 测试 rate-mirrors 检查功能
        QProcess process;
        process.start("which", {"rate-mirrors"});
        process.waitForFinished(3000);
        
        bool installed = (process.exitCode() == 0);
        
        // 这个测试会根据系统环境而变化
        if (installed) {
            qDebug() << "rate-mirrors 已安装";
        } else {
            qDebug() << "rate-mirrors 未安装";
        }
        
        // 无论如何，检查逻辑应该能正常工作
        QVERIFY(process.exitCode() == 0 || process.exitCode() != 0);
    }

    void testExtractMirrorPrefix() {
        QStringList testUrls = {
            "https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch",
            "https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch",
            "http://mirror.example.com/archlinux/$repo/os/$arch"
        };
        
        for (const QString &url : testUrls) {
            QString prefix = url.split("$repo").first();
            
            QVERIFY(!prefix.isEmpty());
            QVERIFY(!prefix.contains("$repo"));
            QVERIFY(!prefix.contains("$arch"));
            
            // 验证提取的前缀
            if (url.contains("tuna")) {
                QCOMPARE(prefix, QString("https://mirrors.tuna.tsinghua.edu.cn/archlinux/"));
            }
        }
    }

    void testValidateMirrorUrl() {
        // 测试镜像 URL 格式验证
        QStringList validUrls = {
            "https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch",
            "http://mirror.example.com/archlinux/$repo/os/$arch",
            "ftp://ftp.example.com/archlinux/$repo/os/$arch"
        };
        
        QStringList invalidUrls = {
            "not a url",
            "invalid url without protocol",
            ""
        };
        
        for (const QString &url : validUrls) {
            QVERIFY(url.contains("://"));
            QVERIFY(url.contains("$repo") || url.contains("$arch"));
        }
        
        for (const QString &url : invalidUrls) {
            QVERIFY(!url.contains("://") || url.isEmpty());
        }
    }

    void testFilterValidMirrors() {
        QStringList testOutput = {
            "# Testing mirrors...",
            "Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch",
            "# Connection failed: timeout",
            "Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch",
            "",
            "# Analysis complete",
            "Server = https://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch"
        };
        
        // 模拟 onSaveButtonClicked 中的过滤逻辑
        QStringList validLines;
        for (const QString &line : testOutput) {
            QString trimmed = line.trimmed();
            if (!trimmed.startsWith("#") && !trimmed.isEmpty() && trimmed.startsWith("Server = ")) {
                validLines.append(line);
            }
        }
        
        // 验证过滤结果
        QCOMPARE(validLines.size(), 3);
        QVERIFY(validLines[0].contains("tuna.tsinghua.edu.cn"));
        QVERIFY(validLines[1].contains("ustc.edu.cn"));
        QVERIFY(validLines[2].contains("bfsu.edu.cn"));
    }

    void testLimitMirrorCount() {
        QStringList mirrors;
        for (int i = 0; i < 10; ++i) {
            mirrors.append(QString("Server = https://mirror%1.example.com/$repo/os/$arch").arg(i));
        }
        
        // 测试限制为前 5 个
        QCOMPARE(mirrors.size(), 10);
        
        if (mirrors.size() > 5) {
            mirrors = mirrors.mid(0, 5);
        }
        
        QCOMPARE(mirrors.size(), 5);
        QVERIFY(mirrors[0].contains("mirror0"));
        QVERIFY(mirrors[4].contains("mirror4"));
        QVERIFY(!mirrors.contains("mirror5"));
    }

    void testEmptyMirrorList() {
        QStringList emptyList;
        
        // 空列表应该被正确处理
        QVERIFY(emptyList.isEmpty());
        
        // 过滤后应该仍然为空
        QStringList filtered;
        for (const QString &line : emptyList) {
            if (!line.trimmed().startsWith("#") && !line.trimmed().isEmpty()) {
                filtered.append(line);
            }
        }
        
        QVERIFY(filtered.isEmpty());
    }

    void testMirrorListWithVariousFormats() {
        QStringList testLines = {
            "Server = https://example.com/$repo/os/$arch",  // 标准格式
            "  Server = https://example2.com/$repo/os/$arch  ",  // 带空格
            "#Server = https://commented.com/$repo/os/$arch",  // 注释掉的
            "# Comment line",  // 纯注释
            "",  // 空行
            "Server=https://nospace.com/$repo/os/$arch"  // 无空格
        };
        
        QStringList validServers;
        for (const QString &line : testLines) {
            QString trimmed = line.trimmed();
            if (!trimmed.startsWith("#") && !trimmed.isEmpty() && trimmed.contains("Server")) {
                validServers.append(trimmed);
            }
        }
        
        // 应该有 3 个有效服务器（前两个和最后一个）
        QCOMPARE(validServers.size(), 3);
    }

    void testCountryNameExtraction() {
        QStringList testLines = {
            "## China",
            "##China",
            "##  China  ",
            "## United States",
            "## South Korea (한국)"
        };
        
        for (const QString &line : testLines) {
            if (line.trimmed().startsWith("## ")) {
                QString country = line.trimmed().mid(3).trimmed();
                QVERIFY(!country.isEmpty());
                
                if (line.contains("China") && !line.contains("States")) {
                    QCOMPARE(country, QString("China"));
                }
            }
        }
    }

    void testMirrorUrlVariables() {
        QString testUrl = "https://mirrors.example.com/archlinux/$repo/os/$arch";
        
        // 验证 URL 包含必要的变量
        QVERIFY(testUrl.contains("$repo"));
        QVERIFY(testUrl.contains("$arch"));
        
        // 模拟变量替换（实际由 pacman 处理）
        QString replaced = testUrl;
        replaced.replace("$repo", "core");
        replaced.replace("$arch", "x86_64");
        
        QVERIFY(replaced.contains("core"));
        QVERIFY(replaced.contains("x86_64"));
        QVERIFY(!replaced.contains("$repo"));
        QVERIFY(!replaced.contains("$arch"));
        
        QCOMPARE(replaced, QString("https://mirrors.example.com/archlinux/core/os/x86_64"));
    }

    void testNetworkTimeout() {
        // 测试网络超时设置
        QNetworkRequest request;
        request.setTransferTimeout(30000); // 30秒
        
        // 验证超时设置
        QCOMPARE(request.transferTimeout(), 30000);
    }

    void testTemporaryFileCreation() {
        QTemporaryFile tempFile;
        QVERIFY(tempFile.open());
        
        QTextStream out(&tempFile);
        out << "https://mirror1.example.com\n";
        out << "https://mirror2.example.com\n";
        out.flush();
        
        tempFile.close();
        
        // 验证文件可以被读取
        QFile readFile(tempFile.fileName());
        QVERIFY(readFile.open(QIODevice::ReadOnly));
        
        QTextStream in(&readFile);
        QString content = in.readAll();
        
        QVERIFY(content.contains("mirror1"));
        QVERIFY(content.contains("mirror2"));
    }

    void testRateMirrorsCommand() {
        // 测试 rate-mirrors 命令参数构建
        QStringList arguments;
        arguments << "stdin"
                  << "--path-to-test=core/os/x86_64/core.db"
                  << "--path-to-return=$repo/os/$arch"
                  << "--comment-prefix=# "
                  << "--output-prefix=Server = ";
        
        QCOMPARE(arguments.size(), 5);
        QCOMPARE(arguments[0], QString("stdin"));
        QVERIFY(arguments[1].contains("core.db"));
        QVERIFY(arguments[4].contains("Server = "));
    }
};

QTEST_MAIN(TestMirrorListWindow)
#include "test_mirrorlist.moc"
